/**
 * @file DroidSansMono15.c
 * @brief C File generated by Microchip Tool
 * Label: __DroidSans_15
 * Description:  Height: 15 pixels, 2 bit per pixel, Range: ' ' to '~'
 * @author Daniel Szot
 */

#include "lib/graphics/graphics.h"

extern const UINT8 __DroidSansMono_15[] __attribute__((aligned(2)));

const struct graphFont g_DroidSansMono15 =
{
    GRAPH_FONT_BITMAP,
    __DroidSansMono_15
};

const UINT8 __DroidSansMono_15[] __attribute__((aligned(2))) =
{
/****************************************
 * Font header
 ****************************************/
    0x00,           // Font ID
    0x04,           // Font information:  2 bits per pixel, Characters zero degress rotation
    0x20, 0x00,     // First Character
    0x7E, 0x00,     // Last Character
    0x0F, 0x00,     // Height
/****************************************
 * Font Glyph Table
 ****************************************/
    0x07,              // width of the glyph
    0x84, 0x01, 0x00,  // Character - 32, offset (0x00000184)
    0x07,              // width of the glyph
    0xA2, 0x01, 0x00,  // Character - 33, offset (0x000001A2)
    0x07,              // width of the glyph
    0xC0, 0x01, 0x00,  // Character - 34, offset (0x000001C0)
    0x07,              // width of the glyph
    0xDE, 0x01, 0x00,  // Character - 35, offset (0x000001DE)
    0x07,              // width of the glyph
    0xFC, 0x01, 0x00,  // Character - 36, offset (0x000001FC)
    0x07,              // width of the glyph
    0x1A, 0x02, 0x00,  // Character - 37, offset (0x0000021A)
    0x07,              // width of the glyph
    0x38, 0x02, 0x00,  // Character - 38, offset (0x00000238)
    0x07,              // width of the glyph
    0x56, 0x02, 0x00,  // Character - 39, offset (0x00000256)
    0x07,              // width of the glyph
    0x74, 0x02, 0x00,  // Character - 40, offset (0x00000274)
    0x07,              // width of the glyph
    0x92, 0x02, 0x00,  // Character - 41, offset (0x00000292)
    0x07,              // width of the glyph
    0xB0, 0x02, 0x00,  // Character - 42, offset (0x000002B0)
    0x07,              // width of the glyph
    0xCE, 0x02, 0x00,  // Character - 43, offset (0x000002CE)
    0x07,              // width of the glyph
    0xEC, 0x02, 0x00,  // Character - 44, offset (0x000002EC)
    0x07,              // width of the glyph
    0x0A, 0x03, 0x00,  // Character - 45, offset (0x0000030A)
    0x07,              // width of the glyph
    0x28, 0x03, 0x00,  // Character - 46, offset (0x00000328)
    0x07,              // width of the glyph
    0x46, 0x03, 0x00,  // Character - 47, offset (0x00000346)
    0x07,              // width of the glyph
    0x64, 0x03, 0x00,  // Character - 48, offset (0x00000364)
    0x07,              // width of the glyph
    0x82, 0x03, 0x00,  // Character - 49, offset (0x00000382)
    0x07,              // width of the glyph
    0xA0, 0x03, 0x00,  // Character - 50, offset (0x000003A0)
    0x07,              // width of the glyph
    0xBE, 0x03, 0x00,  // Character - 51, offset (0x000003BE)
    0x07,              // width of the glyph
    0xDC, 0x03, 0x00,  // Character - 52, offset (0x000003DC)
    0x07,              // width of the glyph
    0xFA, 0x03, 0x00,  // Character - 53, offset (0x000003FA)
    0x07,              // width of the glyph
    0x18, 0x04, 0x00,  // Character - 54, offset (0x00000418)
    0x07,              // width of the glyph
    0x36, 0x04, 0x00,  // Character - 55, offset (0x00000436)
    0x07,              // width of the glyph
    0x54, 0x04, 0x00,  // Character - 56, offset (0x00000454)
    0x07,              // width of the glyph
    0x72, 0x04, 0x00,  // Character - 57, offset (0x00000472)
    0x07,              // width of the glyph
    0x90, 0x04, 0x00,  // Character - 58, offset (0x00000490)
    0x07,              // width of the glyph
    0xAE, 0x04, 0x00,  // Character - 59, offset (0x000004AE)
    0x07,              // width of the glyph
    0xCC, 0x04, 0x00,  // Character - 60, offset (0x000004CC)
    0x07,              // width of the glyph
    0xEA, 0x04, 0x00,  // Character - 61, offset (0x000004EA)
    0x07,              // width of the glyph
    0x08, 0x05, 0x00,  // Character - 62, offset (0x00000508)
    0x07,              // width of the glyph
    0x26, 0x05, 0x00,  // Character - 63, offset (0x00000526)
    0x07,              // width of the glyph
    0x44, 0x05, 0x00,  // Character - 64, offset (0x00000544)
    0x07,              // width of the glyph
    0x62, 0x05, 0x00,  // Character - 65, offset (0x00000562)
    0x07,              // width of the glyph
    0x80, 0x05, 0x00,  // Character - 66, offset (0x00000580)
    0x07,              // width of the glyph
    0x9E, 0x05, 0x00,  // Character - 67, offset (0x0000059E)
    0x07,              // width of the glyph
    0xBC, 0x05, 0x00,  // Character - 68, offset (0x000005BC)
    0x07,              // width of the glyph
    0xDA, 0x05, 0x00,  // Character - 69, offset (0x000005DA)
    0x07,              // width of the glyph
    0xF8, 0x05, 0x00,  // Character - 70, offset (0x000005F8)
    0x07,              // width of the glyph
    0x16, 0x06, 0x00,  // Character - 71, offset (0x00000616)
    0x07,              // width of the glyph
    0x34, 0x06, 0x00,  // Character - 72, offset (0x00000634)
    0x07,              // width of the glyph
    0x52, 0x06, 0x00,  // Character - 73, offset (0x00000652)
    0x07,              // width of the glyph
    0x70, 0x06, 0x00,  // Character - 74, offset (0x00000670)
    0x07,              // width of the glyph
    0x8E, 0x06, 0x00,  // Character - 75, offset (0x0000068E)
    0x07,              // width of the glyph
    0xAC, 0x06, 0x00,  // Character - 76, offset (0x000006AC)
    0x07,              // width of the glyph
    0xCA, 0x06, 0x00,  // Character - 77, offset (0x000006CA)
    0x07,              // width of the glyph
    0xE8, 0x06, 0x00,  // Character - 78, offset (0x000006E8)
    0x07,              // width of the glyph
    0x06, 0x07, 0x00,  // Character - 79, offset (0x00000706)
    0x07,              // width of the glyph
    0x24, 0x07, 0x00,  // Character - 80, offset (0x00000724)
    0x07,              // width of the glyph
    0x42, 0x07, 0x00,  // Character - 81, offset (0x00000742)
    0x07,              // width of the glyph
    0x60, 0x07, 0x00,  // Character - 82, offset (0x00000760)
    0x07,              // width of the glyph
    0x7E, 0x07, 0x00,  // Character - 83, offset (0x0000077E)
    0x07,              // width of the glyph
    0x9C, 0x07, 0x00,  // Character - 84, offset (0x0000079C)
    0x07,              // width of the glyph
    0xBA, 0x07, 0x00,  // Character - 85, offset (0x000007BA)
    0x07,              // width of the glyph
    0xD8, 0x07, 0x00,  // Character - 86, offset (0x000007D8)
    0x07,              // width of the glyph
    0xF6, 0x07, 0x00,  // Character - 87, offset (0x000007F6)
    0x07,              // width of the glyph
    0x14, 0x08, 0x00,  // Character - 88, offset (0x00000814)
    0x07,              // width of the glyph
    0x32, 0x08, 0x00,  // Character - 89, offset (0x00000832)
    0x07,              // width of the glyph
    0x50, 0x08, 0x00,  // Character - 90, offset (0x00000850)
    0x07,              // width of the glyph
    0x6E, 0x08, 0x00,  // Character - 91, offset (0x0000086E)
    0x07,              // width of the glyph
    0x8C, 0x08, 0x00,  // Character - 92, offset (0x0000088C)
    0x07,              // width of the glyph
    0xAA, 0x08, 0x00,  // Character - 93, offset (0x000008AA)
    0x07,              // width of the glyph
    0xC8, 0x08, 0x00,  // Character - 94, offset (0x000008C8)
    0x07,              // width of the glyph
    0xE6, 0x08, 0x00,  // Character - 95, offset (0x000008E6)
    0x07,              // width of the glyph
    0x04, 0x09, 0x00,  // Character - 96, offset (0x00000904)
    0x07,              // width of the glyph
    0x22, 0x09, 0x00,  // Character - 97, offset (0x00000922)
    0x07,              // width of the glyph
    0x40, 0x09, 0x00,  // Character - 98, offset (0x00000940)
    0x07,              // width of the glyph
    0x5E, 0x09, 0x00,  // Character - 99, offset (0x0000095E)
    0x07,              // width of the glyph
    0x7C, 0x09, 0x00,  // Character - 100, offset (0x0000097C)
    0x07,              // width of the glyph
    0x9A, 0x09, 0x00,  // Character - 101, offset (0x0000099A)
    0x07,              // width of the glyph
    0xB8, 0x09, 0x00,  // Character - 102, offset (0x000009B8)
    0x07,              // width of the glyph
    0xD6, 0x09, 0x00,  // Character - 103, offset (0x000009D6)
    0x07,              // width of the glyph
    0xF4, 0x09, 0x00,  // Character - 104, offset (0x000009F4)
    0x07,              // width of the glyph
    0x12, 0x0A, 0x00,  // Character - 105, offset (0x00000A12)
    0x07,              // width of the glyph
    0x30, 0x0A, 0x00,  // Character - 106, offset (0x00000A30)
    0x07,              // width of the glyph
    0x4E, 0x0A, 0x00,  // Character - 107, offset (0x00000A4E)
    0x07,              // width of the glyph
    0x6C, 0x0A, 0x00,  // Character - 108, offset (0x00000A6C)
    0x07,              // width of the glyph
    0x8A, 0x0A, 0x00,  // Character - 109, offset (0x00000A8A)
    0x07,              // width of the glyph
    0xA8, 0x0A, 0x00,  // Character - 110, offset (0x00000AA8)
    0x07,              // width of the glyph
    0xC6, 0x0A, 0x00,  // Character - 111, offset (0x00000AC6)
    0x07,              // width of the glyph
    0xE4, 0x0A, 0x00,  // Character - 112, offset (0x00000AE4)
    0x07,              // width of the glyph
    0x02, 0x0B, 0x00,  // Character - 113, offset (0x00000B02)
    0x07,              // width of the glyph
    0x20, 0x0B, 0x00,  // Character - 114, offset (0x00000B20)
    0x07,              // width of the glyph
    0x3E, 0x0B, 0x00,  // Character - 115, offset (0x00000B3E)
    0x07,              // width of the glyph
    0x5C, 0x0B, 0x00,  // Character - 116, offset (0x00000B5C)
    0x07,              // width of the glyph
    0x7A, 0x0B, 0x00,  // Character - 117, offset (0x00000B7A)
    0x07,              // width of the glyph
    0x98, 0x0B, 0x00,  // Character - 118, offset (0x00000B98)
    0x07,              // width of the glyph
    0xB6, 0x0B, 0x00,  // Character - 119, offset (0x00000BB6)
    0x07,              // width of the glyph
    0xD4, 0x0B, 0x00,  // Character - 120, offset (0x00000BD4)
    0x07,              // width of the glyph
    0xF2, 0x0B, 0x00,  // Character - 121, offset (0x00000BF2)
    0x07,              // width of the glyph
    0x10, 0x0C, 0x00,  // Character - 122, offset (0x00000C10)
    0x07,              // width of the glyph
    0x2E, 0x0C, 0x00,  // Character - 123, offset (0x00000C2E)
    0x07,              // width of the glyph
    0x4C, 0x0C, 0x00,  // Character - 124, offset (0x00000C4C)
    0x07,              // width of the glyph
    0x6A, 0x0C, 0x00,  // Character - 125, offset (0x00000C6A)
    0x07,              // width of the glyph
    0x88, 0x0C, 0x00,  // Character - 126, offset (0x00000C88)
/***********************************
 * Font Characters
 ***********************************/
/***********************************
 * Character - 32
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 33
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x02,         //    X*   
    0xC0, 0x02,         //    X*   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x80, 0x01,         //    *.   
    0x00, 0x00,         //         
    0x80, 0x01,         //    *.   
    0xC0, 0x02,         //    X*   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 34
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x07,         //  X. X.  
    0x1C, 0x07,         //  X. X.  
    0x1C, 0x07,         //  X. X.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 35
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x30, 0x0C,         //   X  X  
    0x34, 0x0D,         //  .X .X  
    0xFF, 0x3F,         // XXXXXXX 
    0x24, 0x09,         //  .* .*  
    0x18, 0x06,         //  *. *.  
    0xFF, 0x3F,         // XXXXXXX 
    0x1C, 0x07,         //  X. X.  
    0x1C, 0x07,         //  X. X.  
    0x0C, 0x03,         //  X  X   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 36
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x00,         //    X    
    0xF4, 0x0B,         //  .XXX*  
    0xDC, 0x05,         //  X.X..  
    0xDC, 0x00,         //  X.X    
    0xFC, 0x00,         //  XXX    
    0xE4, 0x07,         //  .*XX.  
    0xC0, 0x0F,         //    XXX  
    0xC0, 0x0D,         //    X.X  
    0xCC, 0x0E,         //  X X*X  
    0xFC, 0x07,         //  XXXX.  
    0xC0, 0x00,         //    X    
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 37
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1D, 0x0D,         // .X. .X  
    0x33, 0x06,         // X X *.  
    0x73, 0x03,         // X X.X   
    0x9D, 0x02,         // .X.**   
    0xD0, 0x01,         //   .X.   
    0xA0, 0x1D,         //   **.X. 
    0x70, 0x33,         //   X.X X 
    0x24, 0x33,         //  .* X X 
    0x1C, 0x1D,         //  X. .X. 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 38
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x02,         //  *XX*   
    0x5C, 0x03,         //  X..X   
    0x5C, 0x03,         //  X..X   
    0xF8, 0x01,         //  *XX.   
    0xB4, 0x00,         //  .X*    
    0xDC, 0x0D,         //  X.X.X  
    0x5C, 0x0F,         //  X..XX  
    0x5C, 0x1F,         //  X..XX. 
    0xF4, 0x2E,         //  .XX*X* 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 39
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 40
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x80, 0x03,         //    *X   
    0xD0, 0x01,         //   .X.   
    0xA0, 0x00,         //   **    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0xA0, 0x00,         //   **    
    0xD0, 0x01,         //   .X.   
    0x80, 0x02,         //    **   
    0x00, 0x00,         //         

/***********************************
 * Character - 41
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xA0, 0x00,         //   **    
    0xD0, 0x01,         //   .X.   
    0x80, 0x02,         //    **   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x80, 0x02,         //    **   
    0xD0, 0x01,         //   .X.   
    0xA0, 0x00,         //   **    
    0x00, 0x00,         //         

/***********************************
 * Character - 42
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x01,         //   .X.   
    0xD5, 0x15,         // ...X... 
    0xFD, 0x1F,         // .XXXXX. 
    0xB0, 0x03,         //   X*X   
    0x34, 0x07,         //  .X X.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 43
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xFD, 0x1F,         // .XXXXX. 
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 44
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x00,         //   .X    
    0xA0, 0x00,         //   **    
    0x70, 0x00,         //   X.    
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 45
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x03,         //  XXXX   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 46
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x00,         //   XX    
    0xF0, 0x00,         //   XX    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 47
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x0D,         //     .X  
    0x00, 0x07,         //     X.  
    0x40, 0x03,         //    .X   
    0x80, 0x02,         //    **   
    0xD0, 0x01,         //   .X.   
    0xA0, 0x00,         //   **    
    0x70, 0x00,         //   X.    
    0x34, 0x00,         //  .X     
    0x1C, 0x00,         //  X.     
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 48
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x28, 0x0A,         //  ** **  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x28, 0x0A,         //  ** **  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 49
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xE4, 0x01,         //  .*X.   
    0xD8, 0x01,         //  *.X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 50
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x14, 0x0D,         //  .. .X  
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  
    0x40, 0x07,         //    .X.  
    0xC0, 0x02,         //    X*   
    0xA0, 0x00,         //   **    
    0x28, 0x00,         //  **     
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 51
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x07,         //  *XXX.  
    0x14, 0x0D,         //  .. .X  
    0x00, 0x0D,         //     .X  
    0x40, 0x0B,         //    .X*  
    0xF0, 0x07,         //   XXX.  
    0x00, 0x0E,         //     *X  
    0x00, 0x0D,         //     .X  
    0x0C, 0x0E,         //  X  *X  
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 52
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x40, 0x03,         //    .X   
    0x80, 0x03,         //    *X   
    0x90, 0x03,         //   .*X   
    0x60, 0x03,         //   *.X   
    0x64, 0x03,         //  .*.X   
    0x5C, 0x03,         //  X..X   
    0xFC, 0x1F,         //  XXXXX. 
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 53
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x0E,         //     *X  
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  
    0x0C, 0x0A,         //  X  **  
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 54
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x0F,         //   .XXX  
    0x74, 0x00,         //  .X.    
    0x28, 0x00,         //  **     
    0xEC, 0x07,         //  X*XX.  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x28, 0x0E,         //  ** *X  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 55
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x0D,         //     .X  
    0x00, 0x0B,         //     X*  
    0x40, 0x07,         //    .X.  
    0x80, 0x03,         //    *X   
    0xC0, 0x01,         //    X.   
    0xD0, 0x01,         //   .X.   
    0xE0, 0x00,         //   *X    
    0x70, 0x00,         //   X.    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 56
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x78, 0x07,         //  *X.X.  
    0xF4, 0x07,         //  .XXX.  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 57
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x2C, 0x0A,         //  X* **  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xF4, 0x0E,         //  .XX*X  
    0x00, 0x0A,         //     **  
    0x40, 0x07,         //    .X.  
    0xFC, 0x01,         //  XXX.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 58
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x00,         //   XX    
    0xF0, 0x00,         //   XX    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x00,         //   XX    
    0xF0, 0x00,         //   XX    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 59
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x00,         //   XX    
    0xF0, 0x00,         //   XX    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x00,         //   .X    
    0xA0, 0x00,         //   **    
    0x70, 0x00,         //   X.    
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 60
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x0D,         //     .X  
    0xE4, 0x06,         //  .*X*.  
    0x7C, 0x00,         //  XX.    
    0xE4, 0x06,         //  .*X*.  
    0x00, 0x0D,         //     .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 61
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 62
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0xE4, 0x06,         //  .*X*.  
    0x40, 0x0F,         //    .XX  
    0xE4, 0x06,         //  .*X*.  
    0x1C, 0x00,         //  X.     
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 63
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x07,         //  *XXX.  
    0x14, 0x0D,         //  .. .X  
    0x00, 0x0D,         //     .X  
    0x40, 0x07,         //    .X.  
    0xD0, 0x01,         //   .X.   
    0x70, 0x00,         //   X.    
    0x00, 0x00,         //         
    0xA0, 0x00,         //   **    
    0xF0, 0x00,         //   XX    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 64
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x0B,         //  .XXX*  
    0x1D, 0x1C,         // .X.  X. 
    0x06, 0x34,         // *.   .X 
    0xD7, 0x37,         // X..XX.X 
    0x33, 0x37,         // X X X.X 
    0x33, 0x37,         // X X X.X 
    0xE3, 0x1E,         // X *X*X. 
    0x07, 0x00,         // X.      
    0x1D, 0x0C,         // .X.  X  
    0xF4, 0x0B,         //  .XXX*  
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 65
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x01,         //   .X.   
    0xE0, 0x02,         //   *X*   
    0x70, 0x03,         //   X.X   
    0x34, 0x07,         //  .X X.  
    0x28, 0x0A,         //  ** **  
    0xFC, 0x0F,         //  XXXXX  
    0x0D, 0x1C,         // .X   X. 
    0x0A, 0x28,         // **   ** 
    0x07, 0x34,         // X.   .X 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 66
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x07,         //  XXXX.  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0xFC, 0x07,         //  XXXX.  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 67
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xE0, 0x0F,         //   *XXX  
    0x74, 0x05,         //  .X...  
    0x2C, 0x00,         //  X*     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x2C, 0x00,         //  X*     
    0x74, 0x0C,         //  .X. X  
    0xE0, 0x0F,         //   *XXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 68
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x02,         //  XXX*   
    0x5C, 0x07,         //  X..X.  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0x5C, 0x07,         //  X..X.  
    0xFC, 0x01,         //  XXX.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 69
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 70
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 71
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xE0, 0x0B,         //   *XX*  
    0x74, 0x05,         //  .X...  
    0x2C, 0x00,         //  X*     
    0x1C, 0x00,         //  X.     
    0x5C, 0x0F,         //  X..XX  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x78, 0x0D,         //  *X..X  
    0xE0, 0x0F,         //   *XXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 72
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 73
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x0F,         //  *XXXX  
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xF8, 0x0F,         //  *XXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 74
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x8C, 0x03,         //  X *X   
    0xFC, 0x01,         //  XXX.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 75
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x38,         //  X.  *X 
    0x1C, 0x1D,         //  X. .X. 
    0x5C, 0x07,         //  X..X.  
    0xDC, 0x01,         //  X.X.   
    0xEC, 0x01,         //  X*X.   
    0x5C, 0x03,         //  X..X   
    0x1C, 0x0B,         //  X. X*  
    0x1C, 0x1D,         //  X. .X. 
    0x1C, 0x34,         //  X.  .X 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 76
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 77
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x0C, 0x0D,         //  X  .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0x2C, 0x0E,         //  X* *X  
    0x2C, 0x0E,         //  X* *X  
    0x6C, 0x0E,         //  X*.*X  
    0x9C, 0x0D,         //  X.*.X  
    0xDC, 0x0D,         //  X.X.X  
    0xCC, 0x0C,         //  X X X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 78
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0D,         //  X* .X  
    0x2C, 0x0D,         //  X* .X  
    0x5C, 0x0D,         //  X...X  
    0x9C, 0x0D,         //  X.*.X  
    0x5C, 0x0D,         //  X...X  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 79
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x38, 0x0B,         //  *X X*  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x38, 0x0B,         //  *X X*  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 80
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x07,         //  XXXX.  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x5C, 0x0A,         //  X..**  
    0xFC, 0x06,         //  XXX*.  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 81
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x38, 0x0B,         //  *X X*  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x38, 0x0B,         //  *X X*  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x07,         //     X.  
    0x00, 0x0D,         //     .X  
    0x00, 0x00,         //         

/***********************************
 * Character - 82
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x07,         //  XXXX.  
    0x1C, 0x0E,         //  X. *X  
    0x1C, 0x0D,         //  X. .X  
    0x5C, 0x0E,         //  X..*X  
    0xFC, 0x07,         //  XXXX.  
    0x5C, 0x07,         //  X..X.  
    0x1C, 0x0A,         //  X. **  
    0x1C, 0x1D,         //  X. .X. 
    0x1C, 0x34,         //  X.  .X 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 83
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x0F,         //  .XXXX  
    0x2C, 0x05,         //  X* ..  
    0x1C, 0x00,         //  X.     
    0x7C, 0x00,         //  XX.    
    0xE4, 0x07,         //  .*XX.  
    0x40, 0x0F,         //    .XX  
    0x00, 0x0D,         //     .X  
    0x0C, 0x0E,         //  X  *X  
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 84
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x3F,         //  XXXXXX 
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 85
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 86
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x07, 0x34,         // X.   .X 
    0x0A, 0x28,         // **   ** 
    0x0D, 0x1C,         // .X   X. 
    0x1C, 0x0D,         //  X. .X  
    0x28, 0x0A,         //  ** **  
    0x34, 0x07,         //  .X X.  
    0x70, 0x03,         //   X.X   
    0xE0, 0x02,         //   *X*   
    0xD0, 0x01,         //   .X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 87
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x07, 0x34,         // X.   .X 
    0x07, 0x34,         // X.   .X 
    0x07, 0x34,         // X.   .X 
    0xC6, 0x24,         // *. X .* 
    0xD6, 0x25,         // *..X..* 
    0x65, 0x16,         // ..*.*.. 
    0x29, 0x1A,         // .** **. 
    0x1D, 0x1D,         // .X. .X. 
    0x0C, 0x0C,         //  X   X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 88
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x07, 0x34,         // X.   .X 
    0x1D, 0x1D,         // .X. .X. 
    0x34, 0x06,         //  .X *.  
    0xB0, 0x03,         //   X*X   
    0xD0, 0x01,         //   .X.   
    0xB0, 0x03,         //   X*X   
    0x24, 0x06,         //  .* *.  
    0x1D, 0x1D,         // .X. .X. 
    0x07, 0x38,         // X.   *X 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 89
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x07, 0x34,         // X.   .X 
    0x0D, 0x1C,         // .X   X. 
    0x18, 0x09,         //  *. .*  
    0x74, 0x07,         //  .X.X.  
    0xD0, 0x02,         //   .X*   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 90
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x0E,         //     *X  
    0x40, 0x07,         //    .X.  
    0x80, 0x02,         //    **   
    0xD0, 0x01,         //   .X.   
    0xA0, 0x00,         //   **    
    0x74, 0x00,         //  .X.    
    0x2C, 0x00,         //  X*     
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 91
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x03,         //   XXX   
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0xF0, 0x03,         //   XXX   
    0x00, 0x00,         //         

/***********************************
 * Character - 92
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0x34, 0x00,         //  .X     
    0x70, 0x00,         //   X.    
    0xA0, 0x00,         //   **    
    0xD0, 0x01,         //   .X.   
    0x80, 0x02,         //    **   
    0x40, 0x03,         //    .X   
    0x00, 0x07,         //     X.  
    0x00, 0x0D,         //     .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 93
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF0, 0x03,         //   XXX   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0xF0, 0x03,         //   XXX   
    0x00, 0x00,         //         

/***********************************
 * Character - 94
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x01,         //   .X.   
    0xE0, 0x02,         //   *X*   
    0x74, 0x03,         //  .X.X   
    0x24, 0x06,         //  .* *.  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 95
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFF, 0x3F,         // XXXXXXX 
    0x00, 0x00,         //         

/***********************************
 * Character - 96
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x02,         //    X*   
    0x40, 0x03,         //    .X   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 97
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x0B,         //  .XXX*  
    0x14, 0x0D,         //  .. .X  
    0xF4, 0x0F,         //  .XXXX  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0xF8, 0x0E,         //  *XX*X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 98
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xEC, 0x07,         //  X*XX.  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xEC, 0x07,         //  X*XX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 99
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x0F,         //  .XXXX  
    0x6C, 0x0C,         //  X*. X  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x6C, 0x0C,         //  X*. X  
    0xF4, 0x0F,         //  .XXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 100
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  
    0xF4, 0x0E,         //  .XX*X  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xF4, 0x0E,         //  .XX*X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 101
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x1C, 0x0D,         //  X. .X  
    0xFC, 0x0F,         //  XXXXX  
    0x1C, 0x00,         //  X.     
    0x2C, 0x0C,         //  X*  X  
    0xF4, 0x0B,         //  .XXX*  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 102
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x80, 0x0F,         //    *XX  
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xFC, 0x0F,         //  XXXXX  
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 103
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x2F,         //  .XXXX* 
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0xF4, 0x07,         //  .XXX.  
    0x1C, 0x00,         //  X.     
    0xFC, 0x1F,         //  XXXXX. 
    0x1C, 0x34,         //  X.  .X 
    0x1C, 0x34,         //  X.  .X 
    0xF4, 0x1F,         //  .XXXX. 

/***********************************
 * Character - 104
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0xEC, 0x07,         //  X*XX.  
    0x2C, 0x0D,         //  X* .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 105
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD0, 0x01,         //   .X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x01,         //  *XX.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xFC, 0x1F,         //  XXXXX. 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 106
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x40, 0x03,         //    .X   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x03,         //  .XXX   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x40, 0x03,         //    .X   
    0x4C, 0x03,         //  X .X   
    0xFC, 0x01,         //  XXX.   

/***********************************
 * Character - 107
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x2D,         //  X. .X* 
    0x5C, 0x07,         //  X..X.  
    0xDC, 0x01,         //  X.X.   
    0x5C, 0x03,         //  X..X   
    0x1C, 0x09,         //  X. .*  
    0x1C, 0x28,         //  X.  ** 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 108
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x01,         //  *XX.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xFC, 0x1F,         //  XXXXX. 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 109
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xBC, 0x0F,         //  XX*XX  
    0xDC, 0x0D,         //  X.X.X  
    0xDC, 0x0D,         //  X.X.X  
    0xDC, 0x0D,         //  X.X.X  
    0xDC, 0x0D,         //  X.X.X  
    0xDC, 0x0D,         //  X.X.X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 110
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xEC, 0x07,         //  X*XX.  
    0x2C, 0x0D,         //  X* .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 111
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x07,         //  .XXX.  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xF4, 0x07,         //  .XXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 112
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xEC, 0x07,         //  X*XX.  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xEC, 0x07,         //  X*XX.  
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     
    0x1C, 0x00,         //  X.     

/***********************************
 * Character - 113
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF4, 0x0E,         //  .XX*X  
    0x2C, 0x0E,         //  X* *X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x2C, 0x0E,         //  X* *X  
    0xF4, 0x0E,         //  .XX*X  
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  
    0x00, 0x0D,         //     .X  

/***********************************
 * Character - 114
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x70, 0x0F,         //   X.XX  
    0xB0, 0x0C,         //   X* X  
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x70, 0x00,         //   X.    
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 115
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xF8, 0x0F,         //  *XXXX  
    0x1C, 0x05,         //  X. ..  
    0xB8, 0x01,         //  *X*.   
    0x50, 0x0F,         //   ..XX  
    0x0C, 0x0D,         //  X  .X  
    0xFC, 0x07,         //  XXXX.  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 116
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x80, 0x01,         //    *.   
    0xC0, 0x01,         //    X.   
    0xFC, 0x0F,         //  XXXXX  
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x80, 0x0F,         //    *XX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 117
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0D,         //  X. .X  
    0x1C, 0x0E,         //  X. *X  
    0xF4, 0x0E,         //  .XX*X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 118
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x28, 0x0A,         //  ** **  
    0x34, 0x07,         //  .X X.  
    0x70, 0x03,         //   X.X   
    0xA0, 0x02,         //   ***   
    0xD0, 0x01,         //   .X.   
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 119
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xD3, 0x31,         // X .X. X 
    0xE7, 0x36,         // X.*X*.X 
    0x77, 0x37,         // X.X.X.X 
    0x3A, 0x2B,         // **X X** 
    0x2D, 0x1E,         // .X* *X. 
    0x1D, 0x1D,         // .X. .X. 
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 120
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x28, 0x0A,         //  ** **  
    0x74, 0x07,         //  .X.X.  
    0xD0, 0x01,         //   .X.   
    0xD0, 0x01,         //   .X.   
    0x74, 0x07,         //  .X.X.  
    0x1C, 0x0D,         //  X. .X  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 121
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x1C, 0x0D,         //  X. .X  
    0x28, 0x0A,         //  ** **  
    0x34, 0x07,         //  .X X.  
    0x70, 0x03,         //   X.X   
    0xD0, 0x02,         //   .X*   
    0xC0, 0x01,         //    X.   
    0xC0, 0x00,         //    X    
    0x90, 0x00,         //   .*    
    0x7C, 0x00,         //  XX.    

/***********************************
 * Character - 122
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x0A,         //     **  
    0x80, 0x02,         //    **   
    0xA0, 0x00,         //   **    
    0x34, 0x00,         //  .X     
    0xFC, 0x0F,         //  XXXXX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

/***********************************
 * Character - 123
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x40, 0x0F,         //    .XX  
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xD4, 0x01,         //  ..X.   
    0x7C, 0x00,         //  XX.    
    0xD0, 0x01,         //   .X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0xC0, 0x01,         //    X.   
    0x40, 0x0F,         //    .XX  
    0x00, 0x00,         //         

/***********************************
 * Character - 124
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    
    0xC0, 0x00,         //    X    

/***********************************
 * Character - 125
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x7C, 0x00,         //  XX.    
    0xD0, 0x00,         //   .X    
    0xD0, 0x00,         //   .X    
    0xD0, 0x00,         //   .X    
    0xD0, 0x05,         //   .X..  
    0x40, 0x0F,         //    .XX  
    0xD0, 0x01,         //   .X.   
    0xD0, 0x00,         //   .X    
    0xD0, 0x00,         //   .X    
    0xD0, 0x00,         //   .X    
    0x7C, 0x00,         //  XX.    
    0x00, 0x00,         //         

/***********************************
 * Character - 126
 ***********************************/
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0xBC, 0x05,         //  XX*..  
    0x94, 0x0F,         //  ..*XX  
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         
    0x00, 0x00,         //         

};

